apiVersion: v1
kind: Service
metadata:
  name: sentiment-service
spec:
  type: NodePort  # or LoadBalancer if you're on a cloud provider
  selector:
    app: sentiment-api  # must match the label in the deployment
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30011  # only needed if type=NodePort
